### ISSUE TITLE
Add Arabic translations

### ISSUE THREAD

**Issue by izzy** [izzy/d3coder#39]
See #24

**Comment by saifabusaleh** [comment]
hi, can you assign this to me ?

thanks

**Comment by saifabusaleh** [comment]
Hi, @izzy 

I have created translations

I saw also that there is also another issue for arabic translations

i translated what I know

You can take the best of the two

FYI, arabic is Right to left language

**Comment by izzy** [comment]
> FYI, arabic is Right to left language

Yeah, that's why I opened another issue for RTL languages(#62), but since I don't know any arabic and don't know anyone who can read it I can't make a judgement on which one is the better one :/

**Comment by izzy** [comment]
Okay, so this is kinda unfortunate, since we now have 3 possible solutions, #40, #42 and #84 and I honestly have no way of telling which one is the one I should merge and also don't know anyone to check on this one. I'll mark all of them as accepted for the effort but I'd love to see a discussion to which one is the best/most easy to understand translation for native speakers or which one should be the one that's gonna get merged(after possibly discussing improvements)

**Comment by saifabusaleh** [comment]
I have reviewed them and I think #42 is good

**Comment by izzy** [comment]
@saifabusaleh thanks a lot for the help! :)
